version: '2'
services:
  web:
    restart: always
    image: "openagua/rapid-watershed-delineation:latest"
    expose:
     - "8000"
    ports:
     - "80:8000"
#    volumes:
#     - "/data:/home/ubuntu/data"
#    environment:
#      CUENCAS_PATH: "../data"
    command:
      gunicorn app:app -w 2 -b :8000 --name app
    depends_on:
      - rabbit
      - mongo
  worker:
    image: "openagua/rapid-watershed-delineation:latest"
    volumes:
      - "/data:/home/ubuntu/data"
    links:
      - rabbit
    depends_on:
      - rabbit
      - mongo
    command: celery worker -A app.celery
#  nginx:
#    restart: always
#    build: ./nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - web
  rabbit:
      hostname: rabbit
      image: rabbitmq:latest
      environment:
          - RABBITMQ_DEFAULT_USER=rabbitmq
          - RABBITMQ_DEFAULT_PASS=rabbitmq
      ports:
          - "5673:5672"
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo: