version: '2'
services:
  web:
    image: "openagua/rapid-watershed-delineation:latest"
    ports:
     - "80:8000"
    environment:
      CUENCAS_PATH: "~/data"
  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
  mongo:
    image: mongo
    volumes:
      - mongo:/data/db
    ports:
      - "27017:27017"
volumes:
  mongo: